spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saltmerch
    username: jensenyh
    password: password
  application:
      name: backend


server:
  port: 8099
  servlet:
    contextPath: /



